# Name of the pipeline this will be shown in github
name: Build pipeline
# This will trigger the workflow based on a push on main
# or if you'll manually click the button to start a workflow in github actions
on:
  push:
    branches:
      - main
  workflow_dispatch:

# This is the actual heart of the pipeline. you could have more than 1 job which usually contains multiple steps
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Compile with Maven
        run: mvn compile

      - name: Run tests
        run: mvn test

